/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function encode(data: Buffer, symbolSize: number, sourceBlocks: number, alignment: number, repairPackets: number): Array<Buffer>
export declare function getOti(dataLength: number, symbolSize: number, sourceBlocks: number, alignment: number): Buffer
