/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class RaptorQEncoder {
  constructor(data: Buffer, symbolSize: number, sourceBlocks: number, alignment: number)
  getOti(): Buffer
  getPackets(repairPackets: number): Array<Buffer>
}
export declare class RaptorQDecoder {
  constructor(otiHeader: Buffer)
  addPacket(packetBuffer: Buffer): Buffer | null
}
